services:
  todofront:
    container_name: todofront
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'

networks:
  default:
    external: true
    name: nginxproxymanager_default
